builds:
- binary: '{{ .ProjectName }}_v{{ .Version }}'
  main: ./cmd/k8s-promoter
  mod_timestamp: '{{ .CommitTimestamp }}'
  env:
    - CGO_ENABLED=0
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - darwin
    - linux
  goarch:
    - '386'
    - amd64
    - arm
  ignore:
    - goos: darwin
      goarch: '386'
    - goos: darwin
      goarch: arm
release:
  prerelease: auto
