name: release

on:
  push:
    branches:
      - master

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d50f8ea76748df49594d9b109b614f3b4db63c71  # v3.0.0
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@d745f2e74aaf1ee82e747b181f7a0967978abee0 # v6.0
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"

  goreleaser:
    name: Create release
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d50f8ea76748df49594d9b109b614f3b4db63c71  # v3.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@a5865a93f26fcb9014b34e4be3fb246a9691a281 # v3.0.0
        with:
          go-version: 1.17

      - name: Run GoReleaser release
        uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b # v2.9.1
        with:
          distribution: goreleaser
          version: v1.7.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
