name: snapshot

on: [pull_request]

jobs:
  release-snapshot:
    name: Release snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d50f8ea76748df49594d9b109b614f3b4db63c71  # v3.0.0

      - name: Set up Go
        uses: actions/setup-go@a5865a93f26fcb9014b34e4be3fb246a9691a281 # v3.0.0
        with:
          go-version: 1.17

      - uses: actions/cache@2d8d0d1c9b41812b6fd3d4ae064360e7d8762c7b # v3.0.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run GoReleaser build snapshot
        uses: goreleaser/goreleaser-action@0110a4acb73fda6a2c401b6d1cb70a11d5b0fadf # v2.9.1
        with:
          distribution: goreleaser
          version: v1.7.0
          args: build --snapshot --rm-dist
      - name: Archive snapshot binaries
        uses: actions/upload-artifact@v2
        with:
          name: snapshot-binaries
          path: dist
